#include "CPluginSettings.h"
#include "Workspace\Utility\MiscEngine.h"
#include "Workspace\Utility\EngineIterators.h"
#include "Workspace\Utility\CVobCollector.h"
#include "Workspace\Savegame\CSGGlobal.h"
#include "Workspace\Savegame\CSGInstanceSet.h"
#include "Workspace\Savegame\CSGInventoryMonitor.h"
#include "Workspace\Entry\CKeyRemover.h"