#ifdef COMPILE_G1

#define NAMESPACE Gothic_I_Classic
namespace NAMESPACE
{
#define ADDRESS_OCNPC_ONDAMAGE_HIT 0x00731410
#define ADDRESS_ZCWORLD_VOBREMOVEDFROMWORLD 0x005F64C0
#define NPC_HITCHANCE_1H 1
#define NPC_HITCHANCE_2H 2
}

#endif

#ifdef COMPILE_G1A

#define NAMESPACE Gothic_I_Addon
namespace NAMESPACE
{
#define ADDRESS_OCNPC_ONDAMAGE_HIT 0x007700A0
#define ADDRESS_ZCWORLD_VOBREMOVEDFROMWORLD 0x006174A0
#define NPC_HITCHANCE_1H 1
#define NPC_HITCHANCE_2H 2
}

#endif

#ifdef COMPILE_G2

#define NAMESPACE Gothic_II_Classic
namespace NAMESPACE
{
#define ADDRESS_OCNPC_ONDAMAGE_HIT 0x0077D390
#define ADDRESS_ZCWORLD_VOBREMOVEDFROMWORLD 0x0061D1E0
}

#endif

#ifdef COMPILE_G2A

#define NAMESPACE Gothic_II_Addon
namespace NAMESPACE
{
#define ADDRESS_OCNPC_ONDAMAGE_HIT 0x00666610
#define ADDRESS_ZCWORLD_VOBREMOVEDFROMWORLD 0x00624970
}

#endif