#include "Workspace\Savegame\CSGGlobal.cpp"
#include "Workspace\Savegame\CSGInstanceSet.cpp"
#include "Workspace\Savegame\CSGInventoryMonitor.cpp"
#include "Workspace\Savegame\CSGOverlaySet.cpp"

#include "Workspace\Utility\Engine\Misc.cpp"

#include "Workspace\Entry\LoadSettings.cpp"
#include "Workspace\Entry\DrawItem.cpp"
#include "Workspace\Entry\ManageDocs.cpp"
#include "Workspace\Entry\ManageInventory.cpp"
#include "Workspace\Entry\RemoveKeys.cpp"
#include "Workspace\Entry\SaveTorches.cpp"
#include "Workspace\Entry\PrintFocus.cpp"
#include "Workspace\Entry\WaterWeaponFix.cpp"
#include "Workspace\Entry\InventoryFix.cpp"
#include "Workspace\Entry\ThrottleEvents.cpp"
#include "Workspace\Entry\UnconsciousFix.cpp"
#include "Workspace\Entry\MidnightFix.cpp"
#include "Workspace\Entry\FastFood.cpp"
#include "Workspace\Entry\MoveLogEntry.cpp"
